# Generated by Django 4.1.4 on 2022-12-15 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_auto_20221215_1118'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviousReservation',
            fields=[
                ('rental_name', models.CharField(default='Default rental', max_length=64)),
                ('reservation_id', models.IntegerField(primary_key=True, serialize=False)),
                ('reservation_checkin', models.DateField()),
                ('reservation_checkout', models.DateField()),
                ('previous_reservation_id', models.IntegerField()),
            ],
            options={
                'db_table': 'rentals_previous_reservation',
                'managed': False,
            },
        ),
    ]
